version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: autoweave-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
    restart: unless-stopped
    networks:
      - autoweave-network

  memgraph:
    image: memgraph/memgraph:latest
    container_name: autoweave-memgraph
    ports:
      - "7687:7687"
      - "3001:3000"
    volumes:
      - memgraph_data:/var/lib/memgraph
    environment:
      - MEMGRAPH_USER=memgraph
      - MEMGRAPH_PASSWORD=memgraph
    command: ["--log-level=INFO"]
    restart: unless-stopped
    networks:
      - autoweave-network

  redis:
    image: redis:7-alpine
    container_name: autoweave-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - autoweave-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: autoweave-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - autoweave-network

volumes:
  qdrant_data:
  memgraph_data:
  redis_data:

networks:
  autoweave-network:
    driver: bridge