apiVersion: v1
kind: Service
metadata:
  name: memgraph-service
  namespace: autoweave-memory
spec:
  selector:
    app: memgraph
  ports:
    - port: 7687
      targetPort: 7687
      name: bolt
    - port: 3000
      targetPort: 3000
      name: web
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: memgraph-secret
  namespace: autoweave-memory
type: Opaque
data:
  password: YXV0b3dlYXZl  # autoweave

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memgraph
  namespace: autoweave-memory
spec:
  serviceName: memgraph-service
  replicas: 1
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      labels:
        app: memgraph
    spec:
      containers:
      - name: memgraph
        # Use memgraph-mage image which includes MAGE algorithms
        image: memgraph/memgraph-mage:2.11.1
        ports:
        - containerPort: 7687
          name: bolt
        - containerPort: 3000
          name: web
        env:
        - name: MEMGRAPH_USER
          value: "memgraph"
        - name: MEMGRAPH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: memgraph-secret
              key: password
              optional: true
        # Don't override command, use image defaults
        volumeMounts:
        - name: memgraph-storage
          mountPath: /var/lib/memgraph
        - name: memgraph-log
          mountPath: /var/log/memgraph
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - echo 'MATCH (n) RETURN count(n);' | mgconsole --host 127.0.0.1 --port 7687 || exit 1
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 30
          periodSeconds: 10
  volumeClaimTemplates:
  - metadata:
      name: memgraph-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: memgraph-log
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi